services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: adega
      POSTGRES_PASSWORD: adega
      POSTGRES_DB: adega
    ports:
      - "5432:5432"
    volumes:
      - adega_pg:/var/lib/postgresql/data

volumes:
  adega_pg:
